name: Build Request
description: Request a build of a custom image
title: "Build Request: "
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following fields to request a build.

  - type: textarea
    id: build_parameters
    attributes:
      label: Build parameters
      description: |
        Parameters for the image customization. Make sure to keep the same format.
      render: shell
      value: |
        # Ubuntu release to use (22.04, 24.04, ...)
        release=24.04

        # Package to install
        package=your-package

        # Optional: Enable -proposed before installing the package
        #proposed=true

        # Optional: Add a PPA before installing the package
        #ppa=ppa:user/name
    validations:
      required: true
