name: Build, test and release

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Format
      run: cargo fmt --check

    - name: Debug Build
      run: cargo build

    - name: Test Dependencies
      run: sudo apt update && sudo apt install -y qemu-utils

    - name: Intergration tests
      run: sudo ./tests/run-all-tests.sh

    - name: Build
      run: cargo build --release

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: target/release/proposed_package_testing
